import { Intervention } from '../types/intervention';

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/[\s_-]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

const rawInterventions = [
  { id: "anx_001", category: "anxiety_worry", title: "4-7-8 Breathing", type: "breathing", duration_minutes: 3, description: "A slow-breathing technique to calm the nervous system when worry feels overwhelming.", steps: ["Sit comfortably, back straight, hands resting on your lap.", "Exhale completely through your mouth.", "Inhale quietly through your nose for a count of 4.", "Hold your breath for a count of 7.", "Exhale slowly through your mouth for a count of 8, making a soft whoosh sound.", "Repeat this cycle 4 times."], cultural_note: "Can be framed like pranayama, which many Indian users already recognise from yoga — this often increases comfort and adherence.", tags: ["breathing", "quick", "beginner"] },
  { id: "anx_002", category: "anxiety_worry", title: "Worry Time Scheduling", type: "cognitive", duration_minutes: 15, description: "Containing worry to a fixed daily slot instead of letting it run all day.", steps: ["Pick a 15-minute 'worry slot' each day, not close to bedtime.", "Whenever a worry pops up outside this slot, jot it down in one line and tell yourself 'I'll think about this at worry time.'", "During the worry slot, go through your list. For each worry, ask: is this in my control right now?", "For controllable worries, write one small next step. For uncontrollable ones, practice consciously letting them go for the day."], cultural_note: "Useful for family, career, and marriage-related worries that many Indian users carry due to social expectations — the goal isn't to dismiss these pressures but to stop them from occupying every waking hour.", tags: ["journaling", "daily-practice"] },
  { id: "anx_003", category: "anxiety_worry", title: "5-4-3-2-1 Grounding", type: "grounding", duration_minutes: 5, description: "Uses the five senses to pull attention out of anxious thoughts and into the present moment.", steps: ["Name 5 things you can see around you.", "Name 4 things you can physically feel (chair, clothes, floor).", "Name 3 things you can hear.", "Name 2 things you can smell (or like the smell of).", "Name 1 thing you can taste, or are grateful for right now."], cultural_note: "Works well in crowded, noisy home or public settings common in Indian cities — doesn't require privacy or special equipment.", tags: ["grounding", "quick", "crisis-friendly"] },
  { id: "anx_004", category: "anxiety_worry", title: "Reframing Catastrophic Thoughts", type: "cognitive", duration_minutes: 10, description: "A simple CBT thought record to challenge 'worst-case scenario' thinking.", steps: ["Write down the anxious thought exactly as it appears in your mind.", "Ask: what evidence supports this thought? What evidence goes against it?", "Ask: what would I tell a close friend who had this same thought?", "Write a more balanced, realistic version of the thought.", "Rate your anxiety (0-10) before and after."], cultural_note: "Common catastrophic thoughts in India often centre on exam results, job security, marriage prospects, or 'log kya kahenge' (what will people say) — naming these directly in examples can make the exercise feel more relevant.", tags: ["cbt", "thought-record"] },
  { id: "anx_005", category: "anxiety_worry", title: "Progressive Muscle Relaxation (PMR)", type: "relaxation", duration_minutes: 12, description: "Systematically tensing and releasing muscle groups to reduce physical tension from anxiety.", steps: ["Sit or lie down comfortably.", "Starting with your feet, tense the muscles tightly for 5 seconds, then release for 10 seconds, noticing the difference.", "Move upward: calves, thighs, stomach, hands, arms, shoulders, face.", "Finish with 3 slow, deep breaths, noticing the overall looseness in your body."], cultural_note: "Can be positioned as complementary to practices like yoga nidra, which is culturally familiar to many users.", tags: ["relaxation", "body-based"] },
  
  { id: "dep_001", category: "low_mood_depression", title: "Behavioral Activation — One Small Action", type: "behavioral", duration_minutes: 10, description: "Counters low-mood withdrawal by scheduling one small, achievable, pleasant or meaningful activity.", steps: ["List 5 small activities that used to bring you some enjoyment or sense of accomplishment (even simple ones like a short walk or calling a friend).", "Pick the smallest, easiest one to do today.", "Schedule a specific time for it — treat it like an appointment.", "After doing it, note your mood before and after, even if the change is small.", "Repeat with a new small activity tomorrow."], cultural_note: "Frame activities around accessible options — a walk to the local market, chai with a neighbour, a short call to family — rather than assuming access to gyms or paid leisure.", tags: ["behavioral-activation", "daily-practice"] },
  { id: "dep_002", category: "low_mood_depression", title: "Gratitude and Small Wins Log", type: "cognitive", duration_minutes: 5, description: "A brief daily log to counter the negativity bias common in low mood.", steps: ["At the end of the day, write down 1 thing that went okay, however small.", "Write down 1 thing you're grateful for, even something ordinary (a good meal, sunlight, a text from a friend).", "Write down 1 thing you did — not achieved, just did — today.", "Avoid judging the entries as 'too small to count.'"], cultural_note: "Emphasise that gratitude practice is not about denying real struggles (financial stress, family pressure) — it's about widening the lens alongside acknowledging difficulty.", tags: ["journaling", "daily-practice"] },
  { id: "dep_003", category: "low_mood_depression", title: "Identifying Negative Self-Talk Patterns", type: "cognitive", duration_minutes: 10, description: "Helps users notice automatic self-critical thoughts common in depression.", steps: ["Notice a moment you felt low today and recall the thought running through your mind at that time.", "Identify if it fits a pattern: all-or-nothing thinking, self-blame, mind-reading, or 'I'm a burden' type thoughts.", "Ask: is this a fact, or a feeling being treated as fact?", "Write one alternative, more compassionate way to view the situation."], cultural_note: "Many Indian users internalise comparisons ('cousin scored better', 'others got married/promoted already') — naming social comparison explicitly as a thought pattern can increase relevance.", tags: ["cbt", "self-talk"] },
  { id: "dep_004", category: "low_mood_depression", title: "Morning Sunlight and Movement Routine", type: "behavioral", duration_minutes: 15, description: "Uses light exposure and light movement to support mood regulation.", steps: ["Within an hour of waking, step outside or near a window for 10-15 minutes of natural light.", "Combine this with light movement — a walk, stretching, or simple exercises.", "Avoid checking your phone during this time.", "Keep the routine consistent, even on low-motivation days, starting with just 2-3 minutes if needed."], cultural_note: "Terrace, balcony, or rooftop access is common in many Indian homes even without gardens — this can be suggested as a practical substitute for outdoor space.", tags: ["routine", "daily-practice"] },
  { id: "dep_005", category: "low_mood_depression", title: "Values-Based Micro-Goal Setting", type: "behavioral", duration_minutes: 10, description: "Reconnects users with what matters to them through very small, achievable steps.", steps: ["Identify one value that matters to you (e.g., being a good friend, learning, family connection).", "Choose one tiny action today that reflects this value, small enough to feel almost effortless.", "Do the action without waiting to 'feel motivated' first.", "Notice that action can come before motivation, not just after it."], cultural_note: "Values often intersect with duty/family roles in Indian contexts — this can be validated rather than framed as purely individualistic self-actualisation.", tags: ["values", "goal-setting"] },

  { id: "str_001", category: "stress_overwhelm", title: "Brain Dump and Priority Sort", type: "cognitive", duration_minutes: 10, description: "Externalising mental clutter to reduce the feeling of being overwhelmed.", steps: ["Set a timer for 5 minutes and write down everything on your mind — tasks, worries, reminders — without organising.", "Go through the list and mark each item: Urgent, Important-not-urgent, or Can wait.", "Pick just 1-3 items to actually act on today.", "Set the rest aside on paper, not just in your head."], cultural_note: "Useful for joint-family or multi-generational households where responsibilities (financial, caregiving, social obligations) pile up simultaneously.", tags: ["planning", "quick"] },
  { id: "str_002", category: "stress_overwhelm", title: "Box Breathing for Immediate Stress", type: "breathing", duration_minutes: 4, description: "A structured breathing pattern used to quickly lower physiological stress.", steps: ["Inhale through your nose for a count of 4.", "Hold for a count of 4.", "Exhale through your mouth for a count of 4.", "Hold empty for a count of 4.", "Repeat for 4-6 rounds."], cultural_note: "Works discreetly during a commute, exam hall, or work meeting — no equipment or privacy needed.", tags: ["breathing", "quick"] },
  { id: "str_003", category: "stress_overwhelm", title: "Setting One Boundary", type: "behavioral", duration_minutes: 10, description: "Practicing saying no or delegating to reduce chronic overload.", steps: ["Identify one recurring request or task that consistently overwhelms you.", "Draft one polite but clear boundary statement (e.g., 'I can help with this on the weekend, not today').", "Practice saying it out loud once before using it.", "Use it once this week and notice how it feels, without expecting it to be perfect."], cultural_note: "Boundary-setting can feel culturally difficult given strong family/collective obligations — frame this as a skill practiced gradually, not defiance of family values.", tags: ["boundaries", "assertiveness"] },
  { id: "str_004", category: "stress_overwhelm", title: "The 3-Minute Reset", type: "mindfulness", duration_minutes: 3, description: "A short check-in to interrupt stress spirals during a busy day.", steps: ["Pause and ask: what am I feeling right now, in my body and mind?", "Take 3 slow breaths, bringing attention fully to the breath.", "Ask: what does this moment actually need from me right now?", "Take one small action based on the answer, or simply continue with more awareness."], cultural_note: "Can be positioned as a 'mini break' acceptable even in demanding work or study cultures where longer breaks may not be feasible.", tags: ["mindfulness", "quick"] },

  { id: "slp_001", category: "sleep_issues", title: "Wind-Down Routine (60 minutes before bed)", type: "behavioral", duration_minutes: 60, description: "A consistent pre-sleep routine to signal the body it's time to rest.", steps: ["Dim lights and stop screens (or switch to night mode) 30-60 minutes before bed.", "Do a calming activity: light reading, journaling, gentle stretching.", "Avoid heavy meals, caffeine, or intense discussions close to bedtime.", "Keep a consistent bedtime, even on weekends, as much as possible."], cultural_note: "Late dinners and joint TV-watching are common in many Indian households — suggest small adjustments (dimming lights, muting notifications) rather than requiring a separate room.", tags: ["sleep-hygiene", "routine"] },
  { id: "slp_002", category: "sleep_issues", title: "Body Scan for Sleep", type: "relaxation", duration_minutes: 10, description: "A guided attention practice to ease physical tension before sleep.", steps: ["Lie down comfortably and close your eyes.", "Bring attention slowly from your toes up to your head, noticing sensation in each area without trying to change it.", "If your mind wanders to thoughts or worries, gently note 'thinking' and return to the body.", "Let your breathing settle into a slow, natural rhythm."], cultural_note: "Similar in spirit to yoga nidra, which may already feel familiar and trustworthy to Indian users.", tags: ["relaxation", "body-based"] },
  { id: "slp_003", category: "sleep_issues", title: "Racing Thoughts Notebook", type: "cognitive", duration_minutes: 5, description: "Externalising thoughts that keep the mind active at bedtime.", steps: ["Keep a small notebook by your bed.", "If thoughts keep looping as you try to sleep, write them down in short phrases.", "Remind yourself: 'It's written down, I can deal with it tomorrow.'", "Return attention to your breath or body sensations."], cultural_note: "Useful for exam and job-related racing thoughts, very common among Indian students and young professionals.", tags: ["journaling", "sleep-hygiene"] },

  { id: "ang_001", category: "anger_irritability", title: "STOP Technique", type: "behavioral", duration_minutes: 2, description: "A quick pause technique to prevent reacting impulsively when angry.", steps: ["S — Stop what you're doing.", "T — Take a breath, slow and deep.", "O — Observe what you're feeling in your body and thoughts.", "P — Proceed with a chosen response, not an automatic reaction."], cultural_note: "Useful in family arguments where reacting immediately can escalate conflict in close-knit or joint-family settings.", tags: ["quick", "impulse-control"] },
  { id: "ang_002", category: "anger_irritability", title: "Anger Trigger Log", type: "cognitive", duration_minutes: 10, description: "Identifying patterns in what triggers anger to build long-term self-awareness.", steps: ["After an anger episode, note: what happened right before, what I felt in my body, what thought went through my mind, how I reacted.", "Look for patterns after a week of logging (same person, same time of day, same topic).", "Identify one early warning sign (clenched jaw, faster heartbeat) you can catch earlier next time.", "Plan one alternative response for that specific trigger."], cultural_note: "Common triggers reported by Indian users often include family expectations, financial pressure, and workplace hierarchy dynamics — naming these can increase relatability.", tags: ["journaling", "pattern-recognition"] },
  { id: "ang_003", category: "anger_irritability", title: "Physical Release Before Talking", type: "behavioral", duration_minutes: 10, description: "Using movement to discharge physical anger arousal before addressing the issue verbally.", steps: ["When anger feels intense, delay the conversation if possible and move your body: brisk walk, stairs, stretching, or shadow-boxing motions.", "Continue for 5-10 minutes or until physical tension noticeably reduces.", "Once calmer, decide if and how you want to address the issue.", "Approach the conversation using 'I feel...' statements rather than blame."], cultural_note: "Presented as a private, low-cost technique that doesn't require gym access — stairs, terrace pacing, or a short walk outside the home work well.", tags: ["body-based", "de-escalation"] },

  { id: "grf_001", category: "grief_loss", title: "Grief Letter Writing", type: "expressive", duration_minutes: 20, description: "Writing an unsent letter to process feelings related to a loss.", steps: ["Write a letter to the person, relationship, or life stage you've lost, saying what's left unsaid.", "Don't worry about grammar or structure — let it be unfiltered.", "You can keep it, tear it up, or share it with someone you trust — your choice.", "Notice there's no 'right' way to feel while or after writing."], cultural_note: "Can be adapted to align with existing rituals (e.g., writing during a mourning period) rather than positioned as replacing cultural or religious grieving practices.", tags: ["expressive-writing", "grief"] },
  { id: "grf_002", category: "grief_loss", title: "Grief Waves Psychoeducation", type: "psychoeducation", duration_minutes: 5, description: "Normalising the up-and-down, non-linear nature of grief.", steps: ["Understand grief often comes in waves, not a straight line of 'stages' to complete.", "It's common to feel okay one moment and overwhelmed the next — this doesn't mean you're 'doing it wrong.'", "Anniversaries, festivals, or specific triggers can bring grief back strongly even after time has passed.", "Allow yourself to feel this without judging the feeling as 'too much' or 'not enough.'"], cultural_note: "Indian festivals and family gatherings can be intense grief triggers due to the person's visible absence — this can be acknowledged explicitly.", tags: ["psychoeducation"] },

  { id: "fam_001", category: "family_relationship", title: "I-Statements for Difficult Conversations", type: "communication", duration_minutes: 10, description: "A structured way to express concerns without triggering defensiveness.", steps: ["Structure your statement as: 'I feel [emotion] when [specific situation], and I need/want [specific request].'", "Avoid starting with 'You always' or 'You never.'", "Practice saying it once alone before the actual conversation.", "Stay open to the other person's perspective as part of the conversation, not just delivering your point."], cultural_note: "Frame this as strengthening relationships rather than confrontation — often more acceptable in hierarchical family structures when positioned this way.", tags: ["communication", "family"] },
  { id: "fam_002", category: "family_relationship", title: "Separating Duty from Self-Neglect", type: "cognitive", duration_minutes: 10, description: "Reflective exercise to explore the line between family responsibility and personal wellbeing.", steps: ["List your current family or relationship responsibilities.", "For each, ask: is this something I choose to do, or something I feel forced into out of guilt or fear?", "Identify one area where a small amount of self-care wouldn't mean abandoning your responsibilities.", "Try adding that one small act of self-care this week without guilt."], cultural_note: "Designed to respect collectivist values rather than push Western-style individualism — the goal is balance, not rejection of family duty.", tags: ["reflection", "boundaries"] },

  { id: "lon_001", category: "loneliness_isolation", title: "One Small Connection a Day", type: "behavioral", duration_minutes: 10, description: "Building consistent, low-pressure social contact to counter isolation.", steps: ["Identify one person you could reach out to today, even briefly.", "Send a simple message: a check-in, a meme, a memory, or a question.", "You don't need a deep conversation — small, regular contact matters more than intensity.", "Notice you don't have to wait to 'feel like it' to reach out."], cultural_note: "Reconnecting with extended family, neighbours, or old classmates (common social circles in India) can be an accessible starting point.", tags: ["social", "daily-practice"] },
  { id: "lon_002", category: "loneliness_isolation", title: "Community Anchor Activity", type: "behavioral", duration_minutes: 30, description: "Finding a recurring group activity to build a sense of belonging.", steps: ["Think of one group activity you could join or restart: a class, religious gathering, sports group, hobby club, or volunteering.", "Choose one low-pressure option and attend once, without committing long-term yet.", "Notice how you feel afterward, regardless of whether you spoke to many people.", "Decide if you'd like to return, based on your actual experience rather than anxiety beforehand."], cultural_note: "India offers many low-cost or free community spaces (temples, community halls, local sports grounds, NGOs) that can be suggested as accessible options.", tags: ["social", "community"] },

  { id: "pan_001", category: "panic_attacks", title: "Panic Attack Grounding Script", type: "grounding", duration_minutes: 5, description: "An in-the-moment script to use during a panic attack.", steps: ["Remind yourself: 'This is panic. It is intense but not dangerous, and it will pass.'", "Slow your exhale — make it longer than your inhale (inhale 4, exhale 6).", "Press your feet firmly into the ground and notice the physical sensation.", "Name 3 objects you can see in detail around you.", "Wait it out — most panic peaks within 10 minutes and then eases."], cultural_note: "Important to clarify this is not a substitute for medical evaluation if panic attacks are new, frequent, or accompanied by chest pain — encourage a doctor visit to rule out physical causes, which is a common and valid first step in India.", tags: ["crisis-friendly", "grounding"] },
  { id: "pan_002", category: "panic_attacks", title: "Post-Panic Debrief", type: "cognitive", duration_minutes: 10, description: "Reflective exercise after a panic episode to reduce fear of future episodes.", steps: ["Once calm, write down what was happening right before the panic attack.", "Note the physical sensations you experienced (racing heart, dizziness, tight chest).", "Remind yourself these sensations, while frightening, are the body's stress response and not a sign of danger in the moment.", "Identify one grounding technique to try first if it happens again."], cultural_note: "Physical symptoms of panic are sometimes misattributed to purely medical causes — validate seeking medical checkups while also introducing the psychological component gently.", tags: ["reflection", "psychoeducation"] },

  { id: "est_001", category: "self_esteem", title: "Evidence Log Against Self-Criticism", type: "cognitive", duration_minutes: 10, description: "Collecting concrete evidence against harsh self-judgments.", steps: ["Write down a self-critical belief (e.g., 'I'm a failure').", "List concrete counter-evidence from your actual life, however small.", "Notice if the belief is really an old story rather than current truth.", "Write a more balanced statement to replace the harsh one."], cultural_note: "Comparisons around academic/career milestones and marriage timelines are frequent sources of self-esteem struggles in India — naming these directly can help users engage more genuinely.", tags: ["cbt", "self-worth"] },
  { id: "est_002", category: "self_esteem", title: "Strengths Inventory", type: "reflective", duration_minutes: 15, description: "Building a concrete, evidence-based list of personal strengths.", steps: ["List 5 things you're good at, however small or unrelated to grades/career they seem.", "Ask someone who knows you well what they see as your strengths, and add their input.", "Note one strength you used this past week, even in a small situation.", "Revisit this list on hard days as a reminder."], cultural_note: "Encourage strengths beyond academic/professional achievement, since these are often over-emphasised as the sole markers of worth.", tags: ["reflection", "self-worth"] },

  { id: "acd_001", category: "academic_work_pressure", title: "Pomodoro with Compassion Breaks", type: "behavioral", duration_minutes: 25, description: "Structured focus sessions paired with self-compassion, not just productivity.", steps: ["Work in focused blocks of 25 minutes, then take a 5-minute break.", "During the break, do something restorative, not just scroll your phone — stretch, breathe, step outside.", "After every 4 blocks, take a longer 20-30 minute break.", "If a block doesn't go well, avoid harsh self-criticism — simply start the next one."], cultural_note: "Frame rest as part of productivity, not laziness, which can counter strong achievement-oriented pressure common in Indian academic and work culture.", tags: ["productivity", "self-compassion"] },
  { id: "acd_002", category: "academic_work_pressure", title: "Reframing Failure as Data", type: "cognitive", duration_minutes: 10, description: "Shifting from catastrophic thinking about failure to a learning-oriented view.", steps: ["Write down the specific setback (exam, interview, project).", "Separate the event from your identity: 'I did not clear this exam' vs 'I am a failure.'", "Identify one specific, actionable lesson from the experience.", "Write one next step you can take, however small."], cultural_note: "Given intense competitive pressure (entrance exams, limited seats, family expectations), validate that the pressure is real, while still separating outcome from self-worth.", tags: ["cbt", "resilience"] },
  { id: "acd_003", category: "academic_work_pressure", title: "Comparison Detox", type: "behavioral", duration_minutes: 10, description: "Reducing the mental load of constant comparison with peers.", steps: ["Notice when you're comparing yourself to a peer's result, salary, or milestone.", "Pause and ask: does this comparison help me take a useful action, or just make me feel worse?", "If unhelpful, consciously redirect attention to your own next small step.", "Consider a short break from social media if comparisons are frequently triggered there."], cultural_note: "Social comparison is often amplified by extended family/community commentary in India ('so-and-so's son got into IIT') — normalise that this pressure is systemic, not a personal failing to just 'get over.'", tags: ["social-media", "comparison"] },

  { id: "cri_001", category: "crisis_safety", title: "Personal Safety Plan (Basic)", type: "safety_planning", duration_minutes: 15, description: "A simple plan to use when thoughts of self-harm arise, to be created when calm, not in crisis.", steps: ["List your personal warning signs (thoughts, feelings, situations) that things are getting harder.", "List 2-3 coping strategies you can try on your own (breathing, grounding, a distracting activity).", "List 2-3 people you can reach out to, with their contact details noted somewhere accessible.", "Add the crisis helpline numbers (see crisis_resources) to this list.", "Identify how you can make your immediate environment safer if needed (e.g., asking someone to hold onto medications temporarily)."], cultural_note: "Stigma around mental health crises is still significant in many Indian communities — reassure users that creating this plan is a sign of strength and self-care, and that helpline conversations are confidential.", tags: ["safety-planning", "crisis"] },
  { id: "cri_002", category: "crisis_safety", title: "Reasons to Stay List", type: "cognitive", duration_minutes: 10, description: "A reflective list to reconnect with reasons for living during difficult moments, created when relatively calm.", steps: ["Write down people, goals, values, or even small future plans that matter to you.", "Include small things too — a favourite food not yet tried, a show to finish, a place to visit.", "Keep this list somewhere easily accessible (phone notes, a card in your wallet).", "Revisit and add to it over time, even when you're doing okay."], cultural_note: "This exercise is supportive, not a replacement for professional help — always pair with helpline information and encourage professional support if thoughts persist or intensify.", tags: ["reflection", "crisis"] }
];

export const SEED_INTERVENTIONS: Intervention[] = rawInterventions.map((item) => ({
  ...item,
  slug: slugify(item.title),
  short_description: item.description,
  long_description: item.description,
  estimated_duration: item.duration_minutes,
  difficulty: item.duration_minutes <= 5 ? 'easy' : item.duration_minutes <= 15 ? 'medium' : 'hard',
  icon: item.category,
  cover_image: null,
  questions: [
    {
      id: `q_${item.id}_1`,
      prompt: `How did you feel before and after completing ${item.title}?`,
      type: 'text',
    },
  ],
  completion_type: 'guided_steps',
  contraindications: [],
  benefits: [item.description],
  status: 'active',
  content_version: 1,
  created_at: new Date('2026-01-01T00:00:00.000Z').toISOString(),
  updated_at: new Date('2026-01-01T00:00:00.000Z').toISOString(),
}));
