-- Ingress Within Database Compliance Migration (v2.5)
-- Run this in Supabase SQL Editor

-- 1. Add dominant_dimension to assessments table
ALTER TABLE public.assessments 
ADD COLUMN IF NOT EXISTS dominant_dimension TEXT;

-- 2. Add arc_scoring_note to entries table
ALTER TABLE public.entries 
ADD COLUMN IF NOT EXISTS arc_scoring_note TEXT;

-- 3. Add closing_question and classification columns to reflections table
ALTER TABLE public.reflections 
ADD COLUMN IF NOT EXISTS closing_question TEXT,
ADD COLUMN IF NOT EXISTS classification TEXT;

-- Verify columns exist (for audit/observability)
COMMENT ON COLUMN public.assessments.dominant_dimension IS 'Set to whichever single dimension contributes the largest share of Risk Total (Mixed if none > 40%)';
COMMENT ON COLUMN public.entries.arc_scoring_note IS 'Details of arc scoring values when applied';
COMMENT ON COLUMN public.reflections.closing_question IS 'The single closing question generated by the AI';
COMMENT ON COLUMN public.reflections.classification IS 'The Flat, Open, or Scattered pattern classification of the entry';
