import fs from 'fs';
import path from 'path';
import { pathToFileURL } from 'url';
import crypto from 'crypto';

function loadEnv() {
  const envPath = path.resolve(process.cwd(), '.env');
  if (fs.existsSync(envPath)) {
    const content = fs.readFileSync(envPath, 'utf8');
    content.split('\n').forEach(line => {
      if (line.trim().startsWith('#') || !line.trim()) return;
      const match = line.match(/^\s*([\w.-]+)\s*=\s*(.*)?\s*$/);
      if (match) {
        const key = match[1];
        let value = (match[2] || '').trim();
        if (value.startsWith('"') && value.endsWith('"')) {
          value = value.substring(1, value.length - 1);
        } else if (value.startsWith("'") && value.endsWith("'")) {
          value = value.substring(1, value.length - 1);
        }
        process.env[key] = value;
      }
    });
  }
}

loadEnv();

async function runTest() {
  const dbPath = pathToFileURL(path.join(process.cwd(), 'src/lib/db.ts')).href;
  const { supabase: db } = await import(dbPath);

  const knowledgePath = pathToFileURL(path.join(process.cwd(), 'src/lib/knowledge/knowledgeService.ts')).href;
  const { KnowledgeService } = await import(knowledgePath);

  console.log('=== E2E Knowledge Relationship Graph Verification Test ===');

  // 1. Create transient test user
  const email = `test-knowledge-graph-${crypto.randomUUID()}@example.com`;
  const password = 'TestPassword123!';
  const phone = `+1${Math.floor(1000000000 + Math.random() * 9000000000)}`;

  console.log(`Registering auth user: ${email}`);
  const { data: authData, error: authErr } = await db.auth.admin.createUser({
    email,
    password,
    phone,
    email_confirm: true,
    phone_confirm: true
  });

  if (authErr) {
    throw new Error(`Failed to create test auth user: ${authErr.message}`);
  }

  const testUserId = authData.user!.id;
  console.log(`Created Test User ID: ${testUserId}`);
  const testCycleId = crypto.randomUUID();

  // Cleanup helper
  const cleanup = async () => {
    console.log('\nCleaning up database test records...');
    await db.from('knowledge_relationships').delete().eq('user_id', testUserId);
    await db.from('knowledge_cards').delete().eq('user_id', testUserId);
    await db.from('knowledge_profile').delete().eq('user_id', testUserId);
    await db.from('knowledge_events').delete().eq('user_id', testUserId);
    await db.from('profiles').delete().eq('id', testUserId);
    await db.from('users').delete().eq('id', testUserId);
    await db.auth.admin.deleteUser(testUserId);
    console.log('Cleanup finished.');
  };

  try {
    // Setup tables
    await db.from('users').upsert({ id: testUserId, phone_number: phone, name: 'Graph Test User' });
    await db.from('profiles').upsert({ id: testUserId, full_name: 'Graph Test User', phone_number: phone });

    // Mock Contexts
    const mockEventId1 = crypto.randomUUID();
    const mockJournalId1 = crypto.randomUUID();
    const context1 = {
      type: 'journal_entry',
      entry_id: mockJournalId1,
      content: 'I felt intense work pressure at my engineering job. This trigger directly leads to overthinking during difficult tasks.',
      vocabulary: [{ word: 'pressure', normalized: 'pressure', confidence: 1.0 }, { word: 'overthinking', normalized: 'overthinking', confidence: 0.9 }]
    };

    const mockEvent1 = {
      id: mockEventId1,
      user_id: testUserId,
      cycle_id: testCycleId,
      entry_id: mockJournalId1,
      event_type: 'VocabularyUpdated',
      source: 'vocabulary_engine',
      payload: { entry_id: mockJournalId1 }
    };

    // --- TEST 1: Graph Edge Extraction & Strength Reinforcement ---
    console.log('\n--- VERIFICATION 1: Relationship Extraction ---');
    await KnowledgeService.updateGraphWithAI(testUserId, mockEvent1, context1);

    // Verify written relationships
    const { data: edges1 } = await db
      .from('knowledge_relationships')
      .select('*')
      .eq('user_id', testUserId);

    console.log(`Extracted ${edges1?.length || 0} relationships.`);
    if (!edges1 || edges1.length === 0) {
      throw new Error('Failure: No graph edges were generated by the AI.');
    }

    const testEdge = edges1[0];
    console.log(`Edge: [${testEdge.source_node} (${testEdge.source_type})] --(${testEdge.relationship_type})--> [${testEdge.target_node} (${testEdge.target_type})]`);
    console.log(`  Strength: ${testEdge.strength} | Confidence: ${testEdge.confidence}`);
    console.log(`  Supporting Entries cited:`, testEdge.supporting_entries);

    if (!testEdge.source_node || !testEdge.target_node || !testEdge.relationship_type) {
      throw new Error('Schema Failure: Dynamic nodes/edges labels are empty.');
    }
    if (Number(testEdge.strength) !== 0.5 || testEdge.confidence !== 'Low') {
      throw new Error('Schema Failure: initial strength and confidence are incorrect.');
    }
    if (!testEdge.supporting_entries.includes(mockJournalId1)) {
      throw new Error('Citation Failure: Entry citation was not recorded.');
    }
    console.log('✓ Edges extracted and cited correctly!');

    // Reinforce same edge
    console.log('\n--- VERIFICATION 2: Edge Reinforcement ---');
    const mockEventId2 = crypto.randomUUID();
    const mockJournalId2 = crypto.randomUUID();
    const mockEvent2 = {
      id: mockEventId2,
      user_id: testUserId,
      cycle_id: testCycleId,
      entry_id: mockJournalId2,
      event_type: 'VocabularyUpdated',
      source: 'vocabulary_engine',
      payload: { entry_id: mockJournalId2 }
    };

    // Trigger update with same context to reinforce
    await KnowledgeService.updateGraphWithAI(testUserId, mockEvent2, context1);

    const { data: edges2 } = await db
      .from('knowledge_relationships')
      .select('*')
      .eq('user_id', testUserId)
      .eq('source_node', testEdge.source_node)
      .eq('target_node', testEdge.target_node)
      .eq('relationship_type', testEdge.relationship_type);

    const reinforcedEdge = edges2?.[0];
    console.log(`Reinforced Edge Strength: ${reinforcedEdge?.strength} | Confidence: ${reinforcedEdge?.confidence}`);
    console.log(`Citations count: entries=${reinforcedEdge?.supporting_entries?.length}`);
    
    if (Number(reinforcedEdge?.strength) !== 0.6 || reinforcedEdge?.confidence !== 'Medium') {
      throw new Error('Reinforcement Failure: Strength did not increment or confidence did not upgrade.');
    }
    if (reinforcedEdge?.supporting_entries.length !== 2) {
      throw new Error('Citation Failure: Supporting entries did not merge.');
    }
    console.log('✓ Edge strength successfully reinforced and citations merged!');

    // --- TEST 2: Unused Edge Decay ---
    console.log('\n--- VERIFICATION 3: Unused Edge Decay ---');
    const mockEventId3 = crypto.randomUUID();
    const mockJournalId3 = crypto.randomUUID();
    const mockEvent3 = {
      id: mockEventId3,
      user_id: testUserId,
      cycle_id: testCycleId,
      entry_id: mockJournalId3,
      event_type: 'VocabularyUpdated',
      source: 'vocabulary_engine',
      payload: { entry_id: mockJournalId3 }
    };

    // Context that generates a DIFFERENT relationship
    const context3 = {
      type: 'journal_entry',
      entry_id: mockJournalId3,
      content: 'I went for a walk in nature. Walking helps me feel grounded and recovered.',
      vocabulary: [{ word: 'walk', normalized: 'walk', confidence: 1.0 }, { word: 'grounded', normalized: 'grounded', confidence: 1.0 }]
    };

    await KnowledgeService.updateGraphWithAI(testUserId, mockEvent3, context3);

    const { data: edgesAfterDecay } = await db
      .from('knowledge_relationships')
      .select('*')
      .eq('user_id', testUserId)
      .eq('source_node', testEdge.source_node)
      .eq('target_node', testEdge.target_node)
      .eq('relationship_type', testEdge.relationship_type);

    const decayedEdge = edgesAfterDecay?.[0];
    console.log(`Decayed Edge Strength: ${decayedEdge?.strength}`);
    if (Number(decayedEdge?.strength) >= 0.6) {
      throw new Error('Decay Failure: Unused relationship strength did not decrease.');
    }
    console.log('✓ Decay step successfully decayed unused edges!');

    // --- TEST 3: BFS Graph Search ---
    console.log('\n--- VERIFICATION 4: BFS Graph Search ---');
    // Search using a node term
    const searchResult = await KnowledgeService.searchGraph(testUserId, 'pressure');
    console.log('BFS Search Result for "pressure":');
    console.log('Categorized Nodes:', searchResult.categorized_nodes);
    console.log('Connections:', searchResult.connections);
    console.log('Supporting Entries:', searchResult.supporting_entries);

    if (searchResult.connections.length === 0) {
      throw new Error('Search Failure: No connections were found in BFS traversal.');
    }
    if (!searchResult.supporting_entries.includes(mockJournalId1)) {
      throw new Error('Search Failure: Supporting entries list is missing expected citations.');
    }
    console.log('✓ BFS Graph Search traversing hops correctly returning node categories and citations!');

    // --- TEST 4: Profiles and Cards link validation ---
    console.log('\n--- VERIFICATION 5: Profile & Card Node Referencing ---');
    
    const mockProfile = {
      user_id: testUserId,
      identity_model: {
        summary: 'I am a writer.',
        confidence: 'Low' as const,
        supporting_events: { journals: [], reports: [], patterns: [] },
        supporting_vocabulary: [],
        last_updated: new Date().toISOString()
      },
      emotion_model: {
        summary: 'I feel work pressure.',
        confidence: 'High' as const,
        supporting_events: { journals: [mockJournalId1], reports: [], patterns: [] },
        supporting_vocabulary: ['pressure'],
        referenced_nodes: ['work pressure'],
        last_updated: new Date().toISOString()
      },
      vocabulary_model: {
        summary: 'I use pressure language.',
        confidence: 'High' as const,
        supporting_events: { journals: [mockJournalId1], reports: [], patterns: [] },
        supporting_vocabulary: ['pressure'],
        referenced_nodes: ['pressure'],
        last_updated: new Date().toISOString()
      },
      pattern_model: {
        summary: 'I overthink under pressure.',
        confidence: 'High' as const,
        supporting_events: { journals: [mockJournalId1], reports: [], patterns: [] },
        supporting_vocabulary: ['overthinking'],
        referenced_nodes: ['overthinking'],
        last_updated: new Date().toISOString()
      },
      agency_model: {
        summary: 'I feel low agency.',
        confidence: 'High' as const,
        supporting_events: { journals: [mockJournalId1], reports: [], patterns: [] },
        supporting_vocabulary: [],
        referenced_nodes: ['agency'],
        last_updated: new Date().toISOString()
      },
      relationship_model: {
        summary: 'No observations.',
        confidence: 'Low' as const,
        supporting_events: { journals: [], reports: [], patterns: [] },
        supporting_vocabulary: [],
        last_updated: new Date().toISOString()
      },
      decision_model: {
        summary: 'No observations.',
        confidence: 'Low' as const,
        supporting_events: { journals: [], reports: [], patterns: [] },
        supporting_vocabulary: [],
        last_updated: new Date().toISOString()
      },
      growth_model: {
        summary: 'No observations.',
        confidence: 'Low' as const,
        supporting_events: { journals: [], reports: [], patterns: [] },
        supporting_vocabulary: [],
        last_updated: new Date().toISOString()
      },
      communication_model: {
        summary: 'No observations.',
        confidence: 'Low' as const,
        supporting_events: { journals: [], reports: [], patterns: [] },
        supporting_vocabulary: [],
        last_updated: new Date().toISOString()
      },
      stress_model: {
        summary: 'No observations.',
        confidence: 'Low' as const,
        supporting_events: { journals: [], reports: [], patterns: [] },
        supporting_vocabulary: [],
        last_updated: new Date().toISOString()
      },
      values_model: {
        summary: 'No observations.',
        confidence: 'Low' as const,
        supporting_events: { journals: [], reports: [], patterns: [] },
        supporting_vocabulary: [],
        last_updated: new Date().toISOString()
      },
      knowledge_version: '2.0',
      updated_at: new Date().toISOString()
    };

    await db.from('knowledge_profile').upsert(mockProfile);

    // Generate cards using the mock profile
    await (KnowledgeService as any).generateCardsWithAI(testUserId, mockProfile);

    // Verify cards contain node references
    const { data: dbCards } = await db
      .from('knowledge_cards')
      .select('*')
      .eq('user_id', testUserId);

    console.log(`Generated cards count: ${dbCards?.length || 0}`);
    dbCards?.forEach((c: any) => {
      console.log(`Card Type: ${c.card_type} | Referenced Nodes:`, c.referenced_nodes);
      if (!Array.isArray(c.referenced_nodes)) {
        throw new Error('Schema Failure: referenced_nodes column is not an array.');
      }
    });

    console.log('✓ Profile and Cards correctly capture node references!');

    await cleanup();
    console.log('\n=== E2E KNOWLEDGE RELATIONSHIP GRAPH TEST PASSED! ===');

  } catch (err) {
    console.error('\n=== E2E KNOWLEDGE RELATIONSHIP GRAPH TEST FAILED! ===');
    console.error(err);
    await cleanup();
    process.exit(1);
  }
}

runTest().catch(console.error);
